import streamlit as st
from utils.chatbot import AeroGuardBot
import os

def show_floating_chat(context=None):
    """
    Renders a floating chat widget using st.popover.
    context: dict containing 'aqi', 'location', 'risk'
    """
    
    # Custom CSS to float the popover button (if possible) or style it distinctively
    # Note: Streamlit popover doesn't easily allow absolute positioning of the container itself 
    # without breaking interaction, but we can try to place it in the bottom of sidebar 
    # OR leave it as a distinct UI element.
    # A true floating button over content requires hacking Streamlit's iframe structure which is unstable.
    # BEST PRACTICE: "Sticky" bottom sidebar or Main area fixed widget.
    
    # We will try to make a "Fixed" styled container for the button 
    st.markdown("""
    <style>
    /* Style for the popover container to make it look like a floating action button if we could target it */
    /* Since we can't reliably target the exact button ID generated by Streamlit, 
       we will place it in a container and hope for the best or put it in sidebar */
    
    /* Animation for chat messages */
    .stChatMessage {
        animation: fadeIn 0.3s ease-in;
    }
    @keyframes fadeIn {
        from { opacity: 0; transform: translateY(10px); }
        to { opacity: 1; transform: translateY(0); }
    }
    </style>
    """, unsafe_allow_html=True)

    # Initialize Bot Session
    if "chat_messages" not in st.session_state:
        st.session_state.chat_messages = [
            {"role": "assistant", "content": "Hi! I'm AeroBot. Ask me about the air quality!"}
        ]
    
    if "bot_instance" not in st.session_state:
        st.session_state.bot_instance = AeroGuardBot()
    
    # Update context if provided
    if context:
        st.session_state.bot_instance.update_context(context)

    # Floating Action Button Area (Fixed at bottom right via a container if possible, 
    # but for now we put it inside an st.popover which functions as the clickable element)
    
    # We place this in the sidebar at the bottom or main area
    # To simulate "Floating", we can't easily move the button. 
    # Let's verify the user request: "accessible in all pages".
    # Putting it in the SIDEBAR is the most reliable way to exist on all pages.
    
    # Floating Action Button Area
    # We remove 'with st.sidebar' to allow it to be in the main DOM, 
    # then use JS to position it fixed at bottom right.
    
    # CSS/JS Hack for Fixed Bottom Right Position
    st.markdown("""
    <script>
        function fixChatbot() {
            var expanders = window.parent.document.querySelectorAll('.streamlit-expanderHeader');
            for (var i = 0; i < expanders.length; i++) {
                if (expanders[i].innerText.includes("Chat with AeroBot")) {
                    var container = expanders[i].parentElement;
                    container.style.position = 'fixed';
                    container.style.bottom = '20px';
                    container.style.right = '20px';
                    container.style.zIndex = '999999';
                    container.style.width = '350px';
                    container.style.backgroundColor = '#ffffff';
                    container.style.boxShadow = '0px 4px 20px rgba(0,0,0,0.2)';
                    container.style.borderRadius = '12px';
                    container.style.border = '1px solid #e2e8f0';
                    container.style.maxHeight = '80vh';
                    container.style.overflowY = 'auto';
                }
            }
        }
        fixChatbot();
        setInterval(fixChatbot, 1000); // Re-apply on re-renders
    </script>
    """, unsafe_allow_html=True)

    # Expander for Chat (Compatible fallback for st.popover)
    with st.expander("💬 Chat with AeroBot", expanded=False):
        st.markdown("### 🤖 AeroBot Assistant")
        
        # Chat History
        messages_container = st.container()
        with messages_container:
            for message in st.session_state.chat_messages:
                avatar_path = "assets/robot-avatar.png" if message["role"] == "assistant" else None
                if message["role"] == "assistant" and os.path.exists(avatar_path):
                    with st.chat_message(message["role"], avatar=avatar_path):
                        st.markdown(message["content"])
                else:
                    with st.chat_message(message["role"]):
                        st.markdown(message["content"])
                        
        # Input
        # Note: st.chat_input might act strangely inside specific layouts in old versions.
        # If it fails to render at bottom of expander, we might need st.text_input.
        if prompt := st.chat_input("Ask a question...", key="floating_chat_input"):
            # Add user message
            st.session_state.chat_messages.append({"role": "user", "content": prompt})
            # Rerunning to display fresh state is automatic in Streamlit
            
            # Get Response
            response = st.session_state.bot_instance.get_response(prompt)
            
            # Add bot message
            st.session_state.chat_messages.append({"role": "assistant", "content": response})
            st.rerun()
